name: Ping Render Server

on:
  schedule:
    - cron: "*/17 * * * *"  # Cada 26 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer petición al servidor
        run: curl -s -o /dev/null -w "%{http_code}" https://murci.onrender.com/keep_alive
